version: '3.8'

services:
  db:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  web:
    build:
      context: ./django_project
      dockerfile: Dockerfile.prod
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    ports:
    - "8000:8000"
    env_file:
      - ./.env.prod

volumes:
  postgres_data: